2018-03-18 10:40:00 AM-root-INFO-user:Using login function!
2018-03-18 10:59:56 AM-root-INFO-user:Using login function!
2018-03-19 13:56:36 PM-root-INFO-user:Using login function!
2018-03-19 13:56:54 PM-django.request-ERROR-exception:Internal Server Error: /post_weibo/
Traceback (most recent call last):
  File "D:\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python\Python36\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\PythonRelationalFile\MiniWeiboSystem\app01\views\user.py", line 294, in post_weibo
    perm = weibo_data['perm']
KeyError: 'perm'
2018-05-28 18:07:15 PM-root-INFO-user:Using login function!
